<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>404 - Not Found</title>
        <style>
            img {
                display: block;
                margin: 50px auto;
            }
        </style>
    </head>
    <body>
        <h1><img src="/images/404.png" alt="404 Not Found" /></h1>
        <noscript>
            <p>Vous devez <strong>activer Javascript</strong> dans votre navigateur.</p>
        </noscript>
    </body>
</html>
