<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>404 - Not Found</title>
        <style>
            img {
                display: block;
                margin: 50px auto;
            }
        </style>
    </head>
    <body>
        <!--[if lt IE 9]>
        <p class="chromeframe">Vous utilisez un navigateur dépassé. <a href="http://browsehappy.com/">Mettez le à jour maintetant</a> ou <a href="http://www.google.com/chromeframe/?redirect=true">installez Google Chrome Frame</a> pour une meilleur expérience sur ce site.</p>
        <![endif]-->
        <img src="./images/404.png" alt="404 Not Found" />
    </body>
</html>
